import type { Metadata } from "next";
import { Inter, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { SiteHeader } from "@/components/site-header";
import { CustomCursor } from "@/components/custom-cursor";
import { DotPattern } from "@/components/dot-pattern";

const interFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const plusJakartaSansFont = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${interFont.variable} ${plusJakartaSansFont.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans text-foreground">
        <div
          className="pointer-events-none fixed inset-0 -z-10"
          aria-hidden="true"
        >
          <DotPattern
            glow
            width={22}
            height={22}
            className="[mask-image:radial-gradient(ellipse_at_center,white,transparent_42%)]"
          />
        </div>
        <CustomCursor />
        <SiteHeader />
        {children}
      </body>
    </html>
  );
}
